USE [master]
GO
/****** Object:  Database [TDPCRUD]    Script Date: 8/20/2017 10:25:09 PM ******/
CREATE DATABASE [TDPCRUD]
 CONTAINMENT = NONE
GO
ALTER DATABASE [TDPCRUD] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TDPCRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TDPCRUD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TDPCRUD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TDPCRUD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TDPCRUD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TDPCRUD] SET ARITHABORT OFF 
GO
ALTER DATABASE [TDPCRUD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TDPCRUD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TDPCRUD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TDPCRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TDPCRUD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TDPCRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TDPCRUD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TDPCRUD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TDPCRUD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TDPCRUD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TDPCRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TDPCRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TDPCRUD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TDPCRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TDPCRUD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TDPCRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TDPCRUD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TDPCRUD] SET RECOVERY FULL 
GO
ALTER DATABASE [TDPCRUD] SET  MULTI_USER 
GO
ALTER DATABASE [TDPCRUD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TDPCRUD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TDPCRUD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TDPCRUD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TDPCRUD] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TDPCRUD', N'ON'
GO
ALTER DATABASE [TDPCRUD] SET QUERY_STORE = OFF
GO
USE [TDPCRUD]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [TDPCRUD]
GO
/****** Object:  Table [dbo].[Curso]    Script Date: 8/20/2017 10:25:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Curso](
	[IdCurso] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[IdProfesor] [int] NULL,
	[Capacidad] [int] NULL,
 CONSTRAINT [PK_Curso] PRIMARY KEY CLUSTERED 
(
	[IdCurso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Profesor]    Script Date: 8/20/2017 10:25:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesor](
	[IdProfesor] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [varchar](50) NULL,
	[Apellidos] [varchar](50) NULL,
	[Direccion] [varchar](50) NULL,
	[FechaNacimiento] [date] NULL,
 CONSTRAINT [PK_Profesor] PRIMARY KEY CLUSTERED 
(
	[IdProfesor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Curso]  WITH NOCHECK ADD  CONSTRAINT [FK_Curso_Profesor] FOREIGN KEY([IdProfesor])
REFERENCES [dbo].[Profesor] ([IdProfesor])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Curso] CHECK CONSTRAINT [FK_Curso_Profesor]
GO
USE [master]
GO
ALTER DATABASE [TDPCRUD] SET  READ_WRITE 
GO
